DROP TABLE IF EXISTS castings;
DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS actors;

CREATE TABLE films(
 film_id INTEGER PRIMARY KEY AUTO_INCREMENT,
 title VARCHAR (500),
 year INTEGER,
 genre_list VARCHAR(500),
 cast_list VARCHAR(4096)
);