#!/bin/bash
#Script shell développé par Florian BROSSARD

#Vérification de la présence de fichier .c
if [ "$(ls *.c)" == "" ]
then
	echo "Error : C file not found"
	usage
	exit
fi

#Récuperation des noms des fichiers c à compiler
CFILES=$(ls *.c)
EXEC_LIST=$(ls *.c | cut -d. -f1 | tr '\n' ' ')

echo -e "# Generated by generateMakefile.sh\n" > Makefile
echo "CC=gcc" >> Makefile
echo "CFLAGS=-Wall -std=c99 -o2" >> Makefile
echo "EXEC_LIST=$EXEC_LIST" >> Makefile

#Règle all
echo -e "\nall: $EXEC_LIST\n" >> Makefile

#Génération des règles de compilations des fichiers c en fichiers executables
for i in $CFILES
do
	CURR=$(echo $i | cut -d. -f1)
	echo "$CURR: $i" >> Makefile
	echo -e "\t\${CC} \${CFLAGS} -o \$@ $CURR.c\n" >> Makefile
done

#Règle clean
echo "clean:" >> Makefile
echo -e "\t rm -f \${EXEC_LIST}\n" >> Makefile

#Affichage du fichier généré dans le terminal
cat Makefile